spring.application.name=pbprestapi
spring.graphql.schema.locations=classpath*:graphql/**/
spring.graphql.schema.file-extensions=.graphqls,.gqls
spring.graphql.schema.introspection.enabled=true
logging.level.root=trace